# Generated by Django 2.2.3 on 2019-07-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='entityID',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_type',
            field=models.CharField(max_length=64),
        ),
    ]
