# Generated by Django 2.2.3 on 2019-07-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190709_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='entityID',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
