# Generated by Django 2.2 on 2019-04-22 16:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('EMAILVALID', 'EMAILVALID'), ('EMAILINVALID', 'EMAILINVALID'), ('CREATED', 'CREATED'), ('FILLED', 'FILLED'), ('BLOCKED', 'BLOCKED')], db_index=True, max_length=32)),
                ('profile_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('num_connections', models.IntegerField(db_index=True, default=0)),
                ('li_password', models.CharField(max_length=32)),
                ('li_cookies', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'campaign',
            },
        ),
        migrations.CreateModel(
            name='Gmail',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('email', models.CharField(db_index=True, max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('recovery_email', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('INUSE', 'INUSE'), ('BLOCKED', 'BLOCKED'), ('DEAD', 'DEAD')], max_length=32)),
            ],
            options={
                'db_table': 'gmail',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('job_type', models.CharField(choices=[('PWD', 'Password Checker'), ('PC', 'Profile Crawler'), ('B', 'Builder'), ('F', 'Filler'), ('S', 'Searcher'), ('CC', 'Campaign Crawler'), ('CM', 'Campaign Messenger')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('QUEUED', 'QUEUED'), ('STARTED', 'STARTED'), ('ENDED', 'ENDED')], db_index=True, max_length=32)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='app.Account')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='app.Campaign')),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('ip', models.CharField(db_index=True, max_length=32)),
                ('port', models.CharField(max_length=8)),
                ('location', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('INUSE', 'INUSE'), ('BLOCKED', 'BLOCKED'), ('DEAD', 'DEAD')], max_length=32)),
            ],
            options={
                'db_table': 'proxy',
            },
        ),
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='app.Job')),
            ],
            options={
                'db_table': 'job_event',
            },
        ),
        migrations.CreateModel(
            name='AccountEvent',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='app.Account')),
            ],
            options={
                'db_table': 'account_event',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='gmail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.Gmail'),
        ),
        migrations.AddField(
            model_name='account',
            name='proxy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='app.Proxy'),
        ),
    ]
