# Generated by Django 2.2 on 2019-04-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190424_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='li_avatar',
            field=models.CharField(default=str, max_length=64),
        ),
        migrations.AddField(
            model_name='account',
            name='li_default_avatar',
            field=models.CharField(default=str, max_length=64),
        ),
    ]
