# Generated by Django 2.2 on 2019-04-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190425_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='li_default_avatar',
        ),
        migrations.AlterField(
            model_name='account',
            name='li_avatar',
            field=models.CharField(default=str, max_length=128),
        ),
    ]
