# Generated by Django 2.2 on 2019-04-28 13:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190428_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Starter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='excel_files')),
            ],
            options={
                'db_table': 'starter',
            },
        ),
    ]
