# Generated by Django 2.2 on 2019-04-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_starter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starter',
            name='title',
        ),
        migrations.AlterField(
            model_name='starter',
            name='file',
            field=models.FileField(upload_to='excel_files/'),
        ),
    ]
