# Generated by Django 2.2 on 2019-04-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190428_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starter',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
