# Generated by Django 2.2 on 2019-04-28 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190428_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyCreator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'proxy_creator',
            },
        ),
        migrations.RenameModel(
            old_name='Starter',
            new_name='GmailCreator',
        ),
        migrations.AlterModelTable(
            name='gmailcreator',
            table='gmail_creator',
        ),
    ]
