# Generated by Django 2.2 on 2019-04-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190428_1335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GmailCreator',
        ),
        migrations.DeleteModel(
            name='ProxyCreator',
        ),
    ]
