# Generated by Django 2.2 on 2019-05-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190506_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='account',
        ),
    ]
