# Generated by Django 2.2 on 2019-05-07 12:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_campaign_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign', to='app.Campaign')),
            ],
            options={
                'db_table': 'campaign_event',
                'ordering': ['-created_at'],
            },
        ),
    ]
