# Generated by Django 2.2 on 2019-05-07 13:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_campaignevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('type_data', models.CharField(choices=[('COMPANIES', 'company'), ('GROUPS', 'groups'), ('PEOPLE', 'people')], max_length=128)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camp', to='app.Campaign')),
            ],
            options={
                'db_table': 'campaign_data',
            },
        ),
    ]
