# Generated by Django 2.2 on 2019-05-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20190519_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('KEYWORD', 'Search By Keyword'), ('COMPANY', 'Search By Company Name')], default='KEYWORD', max_length=64),
        ),
    ]
