# Generated by Django 2.2 on 2019-05-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20190519_1526'),
        ('app', '0022_auto_20190520_1426'),
    ]

    operations = [
    ]
