# Generated by Django 2.2 on 2019-05-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_merge_20190520_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('PWD', 'Password Changer'), ('PC', 'Profile Crawler'), ('B', 'Builder'), ('F', 'Filler'), ('S', 'Searcher'), ('CCM', 'Campaign Crawler (Manager)'), ('CCW', 'Campaign Crawler (Worker)'), ('CM', 'Campaign Messenger')], db_index=True, max_length=32),
        ),
    ]
