# Generated by Django 2.2 on 2019-05-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190520_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='li_default_avatar',
            field=models.CharField(default='/Users/olegbrusilovski/Documents/_Projects/puppy/project/gunshot-dev/static/assets/default/default.jpg', max_length=128),
        ),
    ]
