# Generated by Django 2.2 on 2019-06-04 14:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20190527_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('num_accounts', models.IntegerField()),
                ('target_locations', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('ready_threshold', models.IntegerField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('STARTED', 'Started'), ('ENDED', 'Ended')], default='NEW', max_length=32)),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='ProfileInfoCombinations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('skills', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('summary', models.CharField(max_length=1024)),
                ('education', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('experience', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('last_name', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'profile_info_combinations',
            },
        ),
    ]
