# Generated by Django 2.2 on 2019-06-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_plan_profileinfocombinations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileInfoCombinations',
            new_name='ProfileInfoCombination',
        ),
        migrations.AlterModelTable(
            name='profileinfocombination',
            table='profile_info_combination',
        ),
    ]
