# Generated by Django 2.2 on 2019-06-04 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_profileinfocombination_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='info', to='app.ProfileInfoCombination'),
        ),
    ]
