# Generated by Django 2.2 on 2019-06-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_account_profile_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='profile_data',
        ),
        migrations.AlterField(
            model_name='profileinfocombination',
            name='summary',
            field=models.CharField(max_length=10024),
        ),
    ]
