# Generated by Django 2.2 on 2019-06-05 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20190605_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account', to='app.ProfileInfoCombination'),
        ),
    ]
