# Generated by Django 2.2 on 2019-06-05 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20190605_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='app.Plan'),
        ),
        migrations.AddField(
            model_name='job',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='app.Plan'),
        ),
        migrations.AddField(
            model_name='job',
            name='scheduled_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='app.ProfileInfoCombination'),
        ),
    ]
