# Generated by Django 2.2 on 2019-06-06 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20190605_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfocombination',
            name='is_male',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='app.Plan'),
        ),
    ]
