# Generated by Django 2.2 on 2019-06-06 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20190606_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='scheduled_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
