# Generated by Django 2.2 on 2019-06-13 10:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20190606_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='events',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
