# Generated by Django 2.2 on 2019-06-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_searcherlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='location',
            field=models.ManyToManyField(to='app.SearcherLocation'),
        ),
    ]
