# Generated by Django 2.2 on 2019-06-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_plan_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='location',
            field=models.ManyToManyField(related_name='name_location', to='app.SearcherLocation'),
        ),
    ]
