# Generated by Django 2.2 on 2019-06-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_plan_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='target_locations',
        ),
    ]
