# Generated by Django 2.2 on 2019-11-21 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_remove_plan_target_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='mail_builder',
            field=models.CharField(choices=[('SILENT', 'Silent'), ('CONDITIONAL', 'Conditional'), ('HARD', 'Hard')], default='SILENT', max_length=32),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('PWD', 'Password Changer'), ('PC', 'Profile Crawler'), ('B', 'Builder'), ('F', 'Filler'), ('S', 'Searcher'), ('CCM', 'Campaign Crawler (Manager)'), ('CCW', 'Campaign Crawler (Worker)'), ('CM', 'Campaign Messenger'), ('V', 'Voter')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='job',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='app.Plan'),
        ),
    ]
