# Generated by Django 2.2 on 2019-11-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20191121_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='mail_builder',
            field=models.CharField(choices=[('IGNORE', 'Ignore'), ('CONDITIONAL', 'Conditional'), ('FORCE', 'Force')], default='IGNORE', max_length=32),
        ),
    ]
