# Generated by Django 2.2 on 2019-11-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20191125_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='company_options',
            field=models.CharField(choices=[('GET_COMPANY_INFO', "Get company's info"), ('GET_EMPLOYEE_INFO', "Get employee's info")], default='GET_COMPANY_INFO', max_length=64),
        ),
    ]
