# Generated by Django 2.2 on 2019-11-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20191125_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='white_list',
            field=models.CharField(help_text="If you are looking for company's employees you can choose positions that you are interested in. Separate values with commas.", max_length=1028, null=True),
        ),
    ]
