# Generated by Django 2.2 on 2019-11-26 15:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20191125_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('keyword', models.CharField(max_length=64)),
                ('get_people', models.BooleanField(default=False, help_text="Get company's employees")),
                ('positions_white_list', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text="Won't work w/o get_people True", null=True)),
                ('max_people', models.IntegerField(blank=True, default=None, null=True)),
                ('max_companies', models.IntegerField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('MANAGER_READY', 'Manager Ready'), ('MANAGER_IN_PROGRESS', 'Manager In Progress'), ('MANAGER_DONE', 'Manager Done'), ('WORKER_READY', 'Worker Ready'), ('WORKER_IN_PROGRESS', 'Worker In Progress'), ('WORKER_DONE', 'Worker Done')], default='MANAGER_READY', max_length=64)),
            ],
            options={
                'db_table': 'campaign_company',
            },
        ),
        migrations.CreateModel(
            name='CampaignPeople',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('keyword', models.CharField(max_length=64)),
                ('company', models.CharField(blank=True, max_length=128, null=True)),
                ('industry', models.CharField(blank=True, max_length=128, null=True)),
                ('mail_builder', models.CharField(choices=[('IGNORE', 'Ignore'), ('CONDITIONAL', 'Conditional'), ('FORCE', 'Force')], default='IGNORE', max_length=32)),
                ('max_people', models.IntegerField(blank=True, default=None, null=True)),
                ('max_pages', models.IntegerField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('MANAGER_READY', 'Manager Ready'), ('MANAGER_IN_PROGRESS', 'Manager In Progress'), ('MANAGER_DONE', 'Manager Done'), ('WORKER_READY', 'Worker Ready'), ('WORKER_IN_PROGRESS', 'Worker In Progress'), ('WORKER_DONE', 'Worker Done')], default='MANAGER_READY', max_length=64)),
            ],
            options={
                'db_table': 'campaign_people',
            },
        ),
    ]
