# Generated by Django 2.2 on 2019-11-27 09:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20191127_0948'),
    ]

    # operations = [
    #     migrations.AlterModelOptions(
    #         name='job',
    #         options={'ordering': ['-created_at']},
    #     ),
    #     migrations.AddField(
    #         model_name='job',
    #         name='scheduled_to',
    #         field=models.DateTimeField(default=django.utils.timezone.now),
    #     ),
    #     migrations.AlterField(
    #         model_name='job',
    #         name='campaign',
    #         field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='app.Campaign'),
    #     ),
    #     migrations.AlterField(
    #         model_name='job',
    #         name='id',
    #         field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
    #     ),
    #     migrations.AlterField(
    #         model_name='job',
    #         name='job_type',
    #         field=models.CharField(choices=[('PWD', 'Password Changer'), ('PC', 'Profile Crawler'), ('B', 'Builder'), ('F', 'Filler'), ('S', 'Searcher'), ('CCM', 'Campaign Crawler (Manager)'), ('CCW', 'Campaign Crawler (Worker)'), ('CM', 'Campaign Messenger'), ('V', 'Voter')], db_index=True, max_length=32),
    #     ),
    #     migrations.AlterField(
    #         model_name='job',
    #         name='status',
    #         field=models.CharField(choices=[('NEW', 'NEW'), ('QUEUED', 'QUEUED'), ('STARTED', 'STARTED'), ('ENDED', 'ENDED')], db_index=True, default='NEW', max_length=32),
    #     ),
    # ]
