# Generated by Django 2.2 on 2019-11-27 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20191127_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='object_id',
        ),
        migrations.AddField(
            model_name='job',
            name='campaign_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='app.CampaignCompany'),
        ),
        migrations.AddField(
            model_name='job',
            name='campaign_people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='app.CampaignPeople'),
        ),
    ]
