# Generated by Django 2.2 on 2019-11-27 12:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_campaigncompanydata_campaigncompanyevent_campaignpeopledata_campaignpeopleevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignpeople',
            name='positions_white_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text="Won't work w/o get_people True", null=True),
        ),
    ]
