# Generated by Django 2.2 on 2019-11-28 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_campaignpeople_positions_white_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignpeople',
            name='max_people',
        ),
        migrations.AlterField(
            model_name='campaignpeople',
            name='max_pages',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
