# Generated by Django 2.2 on 2019-11-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20191128_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncompany',
            name='limit',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='campaigncompany',
            name='page_num',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='campaignpeople',
            name='limit',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='campaignpeople',
            name='page_num',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
