# Generated by Django 2.2 on 2019-12-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_auto_20191203_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigncompanydata',
            name='events',
        ),
        migrations.RemoveField(
            model_name='campaignpeopledata',
            name='events',
        ),
    ]
