# Generated by Django 2.2 on 2019-12-08 13:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_auto_20191203_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('url_list', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list)),
                ('keyword_list', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list)),
                ('serp_index', models.IntegerField(blank=True, default=0)),
                ('target_url', models.CharField(help_text='Write full url address', max_length=128)),
                ('element_text', models.CharField(blank=True, default=str, max_length=128)),
                ('time_delay', models.IntegerField(blank=True, default=0, help_text='Write delay in seconds')),
            ],
            options={
                'db_table': 'page_visitor',
            },
        ),
        migrations.CreateModel(
            name='VisitorEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('event', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitor', to='app.PageVisitor')),
            ],
            options={
                'db_table': 'visitor_event',
                'ordering': ['created_at'],
            },
        ),
    ]
