# Generated by Django 2.2 on 2019-12-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_pagevisitor_visitorevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisitor',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('QUEUED', 'QUEUED'), ('STARTED', 'STARTED'), ('ENDED', 'ENDED')], db_index=True, default='NEW', max_length=32),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('PWD', 'Password Changer'), ('PC', 'Profile Crawler'), ('B', 'Builder'), ('F', 'Filler'), ('S', 'Searcher'), ('CCM', 'Campaign Crawler (Manager)'), ('CCW', 'Campaign Crawler (Worker)'), ('CM', 'Campaign Messenger'), ('V', 'Voter'), ('VIS', 'Visitor')], db_index=True, max_length=32),
        ),
    ]
